version: '3.8'

services:
  app:
    build: .
    container_name: playmatch-app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  postgres:
    image: postgres:16
    container_name: playmatch-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    container_name: playmatch-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    restart: always

volumes:
  pgdata:
  redisdata: